// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  Program = 2,
  Number = 3,
  String = 4,
  Boolean = 5,
  Array = 6,
  ArrayValue = 7,
  Comma = 8,
  Object = 9,
  ObjectKey = 10,
  Identifier = 11,
  Instantiation = 12,
  New = 13,
  FunctionCall = 14
