// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Number = 2,
  String = 3,
  Boolean = 4,
  Array = 5,
  ArrayValue = 6,
  LastArrayValue = 7,
  Object = 8,
  ObjectKey = 9,
  ObjectValue = 10,
  LastObjectValue = 11
