name: "Build"

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  all:
    timeout-minutes: 15
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v3"

      - name: "Setup Go"
        uses: "actions/setup-go@v3"
        with:
          go-version: "^1.18.3"

      - name: "Setup Node"
        uses: "actions/setup-node@v3"
        with:
          node-version: "18.7.0"
          cache: "yarn"
          cache-dependency-path: "frontend/yarn.lock"

      - name: "Test frontend"
        run: |
          make test

      - name: "Build and create archive"
        run: |
          make package build-for-docker

      - name: "Upload to S3"
        if: |
          success() && (github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/master'))
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
          AWS_DEFAULT_OUTPUT: json
        run: |
          make upload-package

      - name: Push Docker images to GHCR
        if: |
          success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          docker build -t ghcr.io/${{ github.actor }}/littletools:latest .
          docker login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
          docker push --all-tags ghcr.io/${{ github.actor }}/littletools
