name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: Write deploy key
        env:
          DEPLOY_KEY_PRIVATE_KEY: "${{ secrets.DEPLOY_KEY_PRIVATE_KEY }}"
        run: |
          mkdir -pv ~/.ssh
          echo "$DEPLOY_KEY_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          git remote set-url origin git@github.com:sharat87/littletools.git

      - name: Build and Publish
        run: make ci
